name: Website CI
run-name: ${{ github.actor }} triggered CI workflow
on:
    push:
        branches: 
            - main
    workflow_dispatch:

jobs: 
    Build_Project:
        runs-on: ubuntu-latest
        steps:
         - name: Check out repository code
           uses: actions/checkout@v4
         - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
            
         - name: Download Node Js
           uses: actions/setup-node@v4
           with:
            node-version: 'latest'
            
         - name: Install packages and build project
           run: |
                cd src/portfolio 
                npm install
                npm run build
            