name: Website CI
run-name: ${{ github.actor }} triggered CI workflow
on:
    push:
        branches: 
            - main
    workflow_dispatch:

jobs: 
    Build_Project:
        runs-on: ubantu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
            
            - run: |
                cd src/portfolio 
